// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: load_pose_stamped.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_load_5fpose_5fstamped_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_load_5fpose_5fstamped_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_load_5fpose_5fstamped_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_load_5fpose_5fstamped_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_load_5fpose_5fstamped_2eproto;
namespace gz_pose_plugin {
class LoadHeader;
class LoadHeaderDefaultTypeInternal;
extern LoadHeaderDefaultTypeInternal _LoadHeader_default_instance_;
class LoadHeader_DataEntry_DoNotUse;
class LoadHeader_DataEntry_DoNotUseDefaultTypeInternal;
extern LoadHeader_DataEntry_DoNotUseDefaultTypeInternal _LoadHeader_DataEntry_DoNotUse_default_instance_;
class LoadHeader_LoadStamp;
class LoadHeader_LoadStampDefaultTypeInternal;
extern LoadHeader_LoadStampDefaultTypeInternal _LoadHeader_LoadStamp_default_instance_;
class LoadPose;
class LoadPoseDefaultTypeInternal;
extern LoadPoseDefaultTypeInternal _LoadPose_default_instance_;
class LoadPoseStamped;
class LoadPoseStampedDefaultTypeInternal;
extern LoadPoseStampedDefaultTypeInternal _LoadPoseStamped_default_instance_;
class LoadPose_Orientation;
class LoadPose_OrientationDefaultTypeInternal;
extern LoadPose_OrientationDefaultTypeInternal _LoadPose_Orientation_default_instance_;
class LoadPose_Position;
class LoadPose_PositionDefaultTypeInternal;
extern LoadPose_PositionDefaultTypeInternal _LoadPose_Position_default_instance_;
}  // namespace gz_pose_plugin
PROTOBUF_NAMESPACE_OPEN
template<> ::gz_pose_plugin::LoadHeader* Arena::CreateMaybeMessage<::gz_pose_plugin::LoadHeader>(Arena*);
template<> ::gz_pose_plugin::LoadHeader_DataEntry_DoNotUse* Arena::CreateMaybeMessage<::gz_pose_plugin::LoadHeader_DataEntry_DoNotUse>(Arena*);
template<> ::gz_pose_plugin::LoadHeader_LoadStamp* Arena::CreateMaybeMessage<::gz_pose_plugin::LoadHeader_LoadStamp>(Arena*);
template<> ::gz_pose_plugin::LoadPose* Arena::CreateMaybeMessage<::gz_pose_plugin::LoadPose>(Arena*);
template<> ::gz_pose_plugin::LoadPoseStamped* Arena::CreateMaybeMessage<::gz_pose_plugin::LoadPoseStamped>(Arena*);
template<> ::gz_pose_plugin::LoadPose_Orientation* Arena::CreateMaybeMessage<::gz_pose_plugin::LoadPose_Orientation>(Arena*);
template<> ::gz_pose_plugin::LoadPose_Position* Arena::CreateMaybeMessage<::gz_pose_plugin::LoadPose_Position>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gz_pose_plugin {

// ===================================================================

class LoadHeader_LoadStamp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gz_pose_plugin.LoadHeader.LoadStamp) */ {
 public:
  inline LoadHeader_LoadStamp() : LoadHeader_LoadStamp(nullptr) {};
  virtual ~LoadHeader_LoadStamp();

  LoadHeader_LoadStamp(const LoadHeader_LoadStamp& from);
  LoadHeader_LoadStamp(LoadHeader_LoadStamp&& from) noexcept
    : LoadHeader_LoadStamp() {
    *this = ::std::move(from);
  }

  inline LoadHeader_LoadStamp& operator=(const LoadHeader_LoadStamp& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadHeader_LoadStamp& operator=(LoadHeader_LoadStamp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoadHeader_LoadStamp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadHeader_LoadStamp* internal_default_instance() {
    return reinterpret_cast<const LoadHeader_LoadStamp*>(
               &_LoadHeader_LoadStamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LoadHeader_LoadStamp& a, LoadHeader_LoadStamp& b) {
    a.Swap(&b);
  }
  inline void Swap(LoadHeader_LoadStamp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadHeader_LoadStamp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoadHeader_LoadStamp* New() const final {
    return CreateMaybeMessage<LoadHeader_LoadStamp>(nullptr);
  }

  LoadHeader_LoadStamp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoadHeader_LoadStamp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoadHeader_LoadStamp& from);
  void MergeFrom(const LoadHeader_LoadStamp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoadHeader_LoadStamp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gz_pose_plugin.LoadHeader.LoadStamp";
  }
  protected:
  explicit LoadHeader_LoadStamp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_load_5fpose_5fstamped_2eproto);
    return ::descriptor_table_load_5fpose_5fstamped_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSecFieldNumber = 1,
    kNsecFieldNumber = 2,
  };
  // int64 sec = 1;
  void clear_sec();
  ::PROTOBUF_NAMESPACE_ID::int64 sec() const;
  void set_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_sec() const;
  void _internal_set_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 nsec = 2;
  void clear_nsec();
  ::PROTOBUF_NAMESPACE_ID::int32 nsec() const;
  void set_nsec(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nsec() const;
  void _internal_set_nsec(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:gz_pose_plugin.LoadHeader.LoadStamp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 sec_;
  ::PROTOBUF_NAMESPACE_ID::int32 nsec_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_load_5fpose_5fstamped_2eproto;
};
// -------------------------------------------------------------------

class LoadHeader_DataEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<LoadHeader_DataEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<LoadHeader_DataEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  LoadHeader_DataEntry_DoNotUse();
  LoadHeader_DataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const LoadHeader_DataEntry_DoNotUse& other);
  static const LoadHeader_DataEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const LoadHeader_DataEntry_DoNotUse*>(&_LoadHeader_DataEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "gz_pose_plugin.LoadHeader.DataEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "gz_pose_plugin.LoadHeader.DataEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_load_5fpose_5fstamped_2eproto);
    return ::descriptor_table_load_5fpose_5fstamped_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class LoadHeader PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gz_pose_plugin.LoadHeader) */ {
 public:
  inline LoadHeader() : LoadHeader(nullptr) {};
  virtual ~LoadHeader();

  LoadHeader(const LoadHeader& from);
  LoadHeader(LoadHeader&& from) noexcept
    : LoadHeader() {
    *this = ::std::move(from);
  }

  inline LoadHeader& operator=(const LoadHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadHeader& operator=(LoadHeader&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoadHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadHeader* internal_default_instance() {
    return reinterpret_cast<const LoadHeader*>(
               &_LoadHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LoadHeader& a, LoadHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(LoadHeader* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoadHeader* New() const final {
    return CreateMaybeMessage<LoadHeader>(nullptr);
  }

  LoadHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoadHeader>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoadHeader& from);
  void MergeFrom(const LoadHeader& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoadHeader* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gz_pose_plugin.LoadHeader";
  }
  protected:
  explicit LoadHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_load_5fpose_5fstamped_2eproto);
    return ::descriptor_table_load_5fpose_5fstamped_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef LoadHeader_LoadStamp LoadStamp;

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kStampFieldNumber = 1,
  };
  // map<string, string> data = 2;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_data();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_data();

  // .gz_pose_plugin.LoadHeader.LoadStamp stamp = 1;
  bool has_stamp() const;
  private:
  bool _internal_has_stamp() const;
  public:
  void clear_stamp();
  const ::gz_pose_plugin::LoadHeader_LoadStamp& stamp() const;
  ::gz_pose_plugin::LoadHeader_LoadStamp* release_stamp();
  ::gz_pose_plugin::LoadHeader_LoadStamp* mutable_stamp();
  void set_allocated_stamp(::gz_pose_plugin::LoadHeader_LoadStamp* stamp);
  private:
  const ::gz_pose_plugin::LoadHeader_LoadStamp& _internal_stamp() const;
  ::gz_pose_plugin::LoadHeader_LoadStamp* _internal_mutable_stamp();
  public:
  void unsafe_arena_set_allocated_stamp(
      ::gz_pose_plugin::LoadHeader_LoadStamp* stamp);
  ::gz_pose_plugin::LoadHeader_LoadStamp* unsafe_arena_release_stamp();

  // @@protoc_insertion_point(class_scope:gz_pose_plugin.LoadHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      LoadHeader_DataEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      0 > data_;
  ::gz_pose_plugin::LoadHeader_LoadStamp* stamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_load_5fpose_5fstamped_2eproto;
};
// -------------------------------------------------------------------

class LoadPose_Position PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gz_pose_plugin.LoadPose.Position) */ {
 public:
  inline LoadPose_Position() : LoadPose_Position(nullptr) {};
  virtual ~LoadPose_Position();

  LoadPose_Position(const LoadPose_Position& from);
  LoadPose_Position(LoadPose_Position&& from) noexcept
    : LoadPose_Position() {
    *this = ::std::move(from);
  }

  inline LoadPose_Position& operator=(const LoadPose_Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadPose_Position& operator=(LoadPose_Position&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoadPose_Position& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadPose_Position* internal_default_instance() {
    return reinterpret_cast<const LoadPose_Position*>(
               &_LoadPose_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(LoadPose_Position& a, LoadPose_Position& b) {
    a.Swap(&b);
  }
  inline void Swap(LoadPose_Position* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadPose_Position* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoadPose_Position* New() const final {
    return CreateMaybeMessage<LoadPose_Position>(nullptr);
  }

  LoadPose_Position* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoadPose_Position>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoadPose_Position& from);
  void MergeFrom(const LoadPose_Position& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoadPose_Position* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gz_pose_plugin.LoadPose.Position";
  }
  protected:
  explicit LoadPose_Position(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_load_5fpose_5fstamped_2eproto);
    return ::descriptor_table_load_5fpose_5fstamped_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:gz_pose_plugin.LoadPose.Position)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double x_;
  double y_;
  double z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_load_5fpose_5fstamped_2eproto;
};
// -------------------------------------------------------------------

class LoadPose_Orientation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gz_pose_plugin.LoadPose.Orientation) */ {
 public:
  inline LoadPose_Orientation() : LoadPose_Orientation(nullptr) {};
  virtual ~LoadPose_Orientation();

  LoadPose_Orientation(const LoadPose_Orientation& from);
  LoadPose_Orientation(LoadPose_Orientation&& from) noexcept
    : LoadPose_Orientation() {
    *this = ::std::move(from);
  }

  inline LoadPose_Orientation& operator=(const LoadPose_Orientation& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadPose_Orientation& operator=(LoadPose_Orientation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoadPose_Orientation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadPose_Orientation* internal_default_instance() {
    return reinterpret_cast<const LoadPose_Orientation*>(
               &_LoadPose_Orientation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(LoadPose_Orientation& a, LoadPose_Orientation& b) {
    a.Swap(&b);
  }
  inline void Swap(LoadPose_Orientation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadPose_Orientation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoadPose_Orientation* New() const final {
    return CreateMaybeMessage<LoadPose_Orientation>(nullptr);
  }

  LoadPose_Orientation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoadPose_Orientation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoadPose_Orientation& from);
  void MergeFrom(const LoadPose_Orientation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoadPose_Orientation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gz_pose_plugin.LoadPose.Orientation";
  }
  protected:
  explicit LoadPose_Orientation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_load_5fpose_5fstamped_2eproto);
    return ::descriptor_table_load_5fpose_5fstamped_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
  };
  // double w = 1;
  void clear_w();
  double w() const;
  void set_w(double value);
  private:
  double _internal_w() const;
  void _internal_set_w(double value);
  public:

  // double x = 2;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 3;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 4;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:gz_pose_plugin.LoadPose.Orientation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double w_;
  double x_;
  double y_;
  double z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_load_5fpose_5fstamped_2eproto;
};
// -------------------------------------------------------------------

class LoadPose PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gz_pose_plugin.LoadPose) */ {
 public:
  inline LoadPose() : LoadPose(nullptr) {};
  virtual ~LoadPose();

  LoadPose(const LoadPose& from);
  LoadPose(LoadPose&& from) noexcept
    : LoadPose() {
    *this = ::std::move(from);
  }

  inline LoadPose& operator=(const LoadPose& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadPose& operator=(LoadPose&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoadPose& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadPose* internal_default_instance() {
    return reinterpret_cast<const LoadPose*>(
               &_LoadPose_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(LoadPose& a, LoadPose& b) {
    a.Swap(&b);
  }
  inline void Swap(LoadPose* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadPose* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoadPose* New() const final {
    return CreateMaybeMessage<LoadPose>(nullptr);
  }

  LoadPose* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoadPose>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoadPose& from);
  void MergeFrom(const LoadPose& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoadPose* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gz_pose_plugin.LoadPose";
  }
  protected:
  explicit LoadPose(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_load_5fpose_5fstamped_2eproto);
    return ::descriptor_table_load_5fpose_5fstamped_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef LoadPose_Position Position;
  typedef LoadPose_Orientation Orientation;

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kOrientationFieldNumber = 2,
  };
  // .gz_pose_plugin.LoadPose.Position position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::gz_pose_plugin::LoadPose_Position& position() const;
  ::gz_pose_plugin::LoadPose_Position* release_position();
  ::gz_pose_plugin::LoadPose_Position* mutable_position();
  void set_allocated_position(::gz_pose_plugin::LoadPose_Position* position);
  private:
  const ::gz_pose_plugin::LoadPose_Position& _internal_position() const;
  ::gz_pose_plugin::LoadPose_Position* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::gz_pose_plugin::LoadPose_Position* position);
  ::gz_pose_plugin::LoadPose_Position* unsafe_arena_release_position();

  // .gz_pose_plugin.LoadPose.Orientation orientation = 2;
  bool has_orientation() const;
  private:
  bool _internal_has_orientation() const;
  public:
  void clear_orientation();
  const ::gz_pose_plugin::LoadPose_Orientation& orientation() const;
  ::gz_pose_plugin::LoadPose_Orientation* release_orientation();
  ::gz_pose_plugin::LoadPose_Orientation* mutable_orientation();
  void set_allocated_orientation(::gz_pose_plugin::LoadPose_Orientation* orientation);
  private:
  const ::gz_pose_plugin::LoadPose_Orientation& _internal_orientation() const;
  ::gz_pose_plugin::LoadPose_Orientation* _internal_mutable_orientation();
  public:
  void unsafe_arena_set_allocated_orientation(
      ::gz_pose_plugin::LoadPose_Orientation* orientation);
  ::gz_pose_plugin::LoadPose_Orientation* unsafe_arena_release_orientation();

  // @@protoc_insertion_point(class_scope:gz_pose_plugin.LoadPose)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::gz_pose_plugin::LoadPose_Position* position_;
  ::gz_pose_plugin::LoadPose_Orientation* orientation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_load_5fpose_5fstamped_2eproto;
};
// -------------------------------------------------------------------

class LoadPoseStamped PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gz_pose_plugin.LoadPoseStamped) */ {
 public:
  inline LoadPoseStamped() : LoadPoseStamped(nullptr) {};
  virtual ~LoadPoseStamped();

  LoadPoseStamped(const LoadPoseStamped& from);
  LoadPoseStamped(LoadPoseStamped&& from) noexcept
    : LoadPoseStamped() {
    *this = ::std::move(from);
  }

  inline LoadPoseStamped& operator=(const LoadPoseStamped& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadPoseStamped& operator=(LoadPoseStamped&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoadPoseStamped& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadPoseStamped* internal_default_instance() {
    return reinterpret_cast<const LoadPoseStamped*>(
               &_LoadPoseStamped_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(LoadPoseStamped& a, LoadPoseStamped& b) {
    a.Swap(&b);
  }
  inline void Swap(LoadPoseStamped* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadPoseStamped* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoadPoseStamped* New() const final {
    return CreateMaybeMessage<LoadPoseStamped>(nullptr);
  }

  LoadPoseStamped* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoadPoseStamped>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoadPoseStamped& from);
  void MergeFrom(const LoadPoseStamped& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoadPoseStamped* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gz_pose_plugin.LoadPoseStamped";
  }
  protected:
  explicit LoadPoseStamped(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_load_5fpose_5fstamped_2eproto);
    return ::descriptor_table_load_5fpose_5fstamped_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kPoseFieldNumber = 2,
  };
  // .gz_pose_plugin.LoadHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::gz_pose_plugin::LoadHeader& header() const;
  ::gz_pose_plugin::LoadHeader* release_header();
  ::gz_pose_plugin::LoadHeader* mutable_header();
  void set_allocated_header(::gz_pose_plugin::LoadHeader* header);
  private:
  const ::gz_pose_plugin::LoadHeader& _internal_header() const;
  ::gz_pose_plugin::LoadHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::gz_pose_plugin::LoadHeader* header);
  ::gz_pose_plugin::LoadHeader* unsafe_arena_release_header();

  // .gz_pose_plugin.LoadPose pose = 2;
  bool has_pose() const;
  private:
  bool _internal_has_pose() const;
  public:
  void clear_pose();
  const ::gz_pose_plugin::LoadPose& pose() const;
  ::gz_pose_plugin::LoadPose* release_pose();
  ::gz_pose_plugin::LoadPose* mutable_pose();
  void set_allocated_pose(::gz_pose_plugin::LoadPose* pose);
  private:
  const ::gz_pose_plugin::LoadPose& _internal_pose() const;
  ::gz_pose_plugin::LoadPose* _internal_mutable_pose();
  public:
  void unsafe_arena_set_allocated_pose(
      ::gz_pose_plugin::LoadPose* pose);
  ::gz_pose_plugin::LoadPose* unsafe_arena_release_pose();

  // @@protoc_insertion_point(class_scope:gz_pose_plugin.LoadPoseStamped)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::gz_pose_plugin::LoadHeader* header_;
  ::gz_pose_plugin::LoadPose* pose_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_load_5fpose_5fstamped_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoadHeader_LoadStamp

// int64 sec = 1;
inline void LoadHeader_LoadStamp::clear_sec() {
  sec_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 LoadHeader_LoadStamp::_internal_sec() const {
  return sec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 LoadHeader_LoadStamp::sec() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadHeader.LoadStamp.sec)
  return _internal_sec();
}
inline void LoadHeader_LoadStamp::_internal_set_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  sec_ = value;
}
inline void LoadHeader_LoadStamp::set_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_sec(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadHeader.LoadStamp.sec)
}

// int32 nsec = 2;
inline void LoadHeader_LoadStamp::clear_nsec() {
  nsec_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoadHeader_LoadStamp::_internal_nsec() const {
  return nsec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 LoadHeader_LoadStamp::nsec() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadHeader.LoadStamp.nsec)
  return _internal_nsec();
}
inline void LoadHeader_LoadStamp::_internal_set_nsec(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nsec_ = value;
}
inline void LoadHeader_LoadStamp::set_nsec(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nsec(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadHeader.LoadStamp.nsec)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// LoadHeader

// .gz_pose_plugin.LoadHeader.LoadStamp stamp = 1;
inline bool LoadHeader::_internal_has_stamp() const {
  return this != internal_default_instance() && stamp_ != nullptr;
}
inline bool LoadHeader::has_stamp() const {
  return _internal_has_stamp();
}
inline void LoadHeader::clear_stamp() {
  if (GetArena() == nullptr && stamp_ != nullptr) {
    delete stamp_;
  }
  stamp_ = nullptr;
}
inline const ::gz_pose_plugin::LoadHeader_LoadStamp& LoadHeader::_internal_stamp() const {
  const ::gz_pose_plugin::LoadHeader_LoadStamp* p = stamp_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gz_pose_plugin::LoadHeader_LoadStamp*>(
      &::gz_pose_plugin::_LoadHeader_LoadStamp_default_instance_);
}
inline const ::gz_pose_plugin::LoadHeader_LoadStamp& LoadHeader::stamp() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadHeader.stamp)
  return _internal_stamp();
}
inline void LoadHeader::unsafe_arena_set_allocated_stamp(
    ::gz_pose_plugin::LoadHeader_LoadStamp* stamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stamp_);
  }
  stamp_ = stamp;
  if (stamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gz_pose_plugin.LoadHeader.stamp)
}
inline ::gz_pose_plugin::LoadHeader_LoadStamp* LoadHeader::release_stamp() {
  auto temp = unsafe_arena_release_stamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gz_pose_plugin::LoadHeader_LoadStamp* LoadHeader::unsafe_arena_release_stamp() {
  // @@protoc_insertion_point(field_release:gz_pose_plugin.LoadHeader.stamp)
  
  ::gz_pose_plugin::LoadHeader_LoadStamp* temp = stamp_;
  stamp_ = nullptr;
  return temp;
}
inline ::gz_pose_plugin::LoadHeader_LoadStamp* LoadHeader::_internal_mutable_stamp() {
  
  if (stamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::gz_pose_plugin::LoadHeader_LoadStamp>(GetArena());
    stamp_ = p;
  }
  return stamp_;
}
inline ::gz_pose_plugin::LoadHeader_LoadStamp* LoadHeader::mutable_stamp() {
  // @@protoc_insertion_point(field_mutable:gz_pose_plugin.LoadHeader.stamp)
  return _internal_mutable_stamp();
}
inline void LoadHeader::set_allocated_stamp(::gz_pose_plugin::LoadHeader_LoadStamp* stamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete stamp_;
  }
  if (stamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(stamp);
    if (message_arena != submessage_arena) {
      stamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stamp, submessage_arena);
    }
    
  } else {
    
  }
  stamp_ = stamp;
  // @@protoc_insertion_point(field_set_allocated:gz_pose_plugin.LoadHeader.stamp)
}

// map<string, string> data = 2;
inline int LoadHeader::_internal_data_size() const {
  return data_.size();
}
inline int LoadHeader::data_size() const {
  return _internal_data_size();
}
inline void LoadHeader::clear_data() {
  data_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
LoadHeader::_internal_data() const {
  return data_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
LoadHeader::data() const {
  // @@protoc_insertion_point(field_map:gz_pose_plugin.LoadHeader.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
LoadHeader::_internal_mutable_data() {
  return data_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
LoadHeader::mutable_data() {
  // @@protoc_insertion_point(field_mutable_map:gz_pose_plugin.LoadHeader.data)
  return _internal_mutable_data();
}

// -------------------------------------------------------------------

// LoadPose_Position

// double x = 1;
inline void LoadPose_Position::clear_x() {
  x_ = 0;
}
inline double LoadPose_Position::_internal_x() const {
  return x_;
}
inline double LoadPose_Position::x() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.Position.x)
  return _internal_x();
}
inline void LoadPose_Position::_internal_set_x(double value) {
  
  x_ = value;
}
inline void LoadPose_Position::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadPose.Position.x)
}

// double y = 2;
inline void LoadPose_Position::clear_y() {
  y_ = 0;
}
inline double LoadPose_Position::_internal_y() const {
  return y_;
}
inline double LoadPose_Position::y() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.Position.y)
  return _internal_y();
}
inline void LoadPose_Position::_internal_set_y(double value) {
  
  y_ = value;
}
inline void LoadPose_Position::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadPose.Position.y)
}

// double z = 3;
inline void LoadPose_Position::clear_z() {
  z_ = 0;
}
inline double LoadPose_Position::_internal_z() const {
  return z_;
}
inline double LoadPose_Position::z() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.Position.z)
  return _internal_z();
}
inline void LoadPose_Position::_internal_set_z(double value) {
  
  z_ = value;
}
inline void LoadPose_Position::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadPose.Position.z)
}

// -------------------------------------------------------------------

// LoadPose_Orientation

// double w = 1;
inline void LoadPose_Orientation::clear_w() {
  w_ = 0;
}
inline double LoadPose_Orientation::_internal_w() const {
  return w_;
}
inline double LoadPose_Orientation::w() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.Orientation.w)
  return _internal_w();
}
inline void LoadPose_Orientation::_internal_set_w(double value) {
  
  w_ = value;
}
inline void LoadPose_Orientation::set_w(double value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadPose.Orientation.w)
}

// double x = 2;
inline void LoadPose_Orientation::clear_x() {
  x_ = 0;
}
inline double LoadPose_Orientation::_internal_x() const {
  return x_;
}
inline double LoadPose_Orientation::x() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.Orientation.x)
  return _internal_x();
}
inline void LoadPose_Orientation::_internal_set_x(double value) {
  
  x_ = value;
}
inline void LoadPose_Orientation::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadPose.Orientation.x)
}

// double y = 3;
inline void LoadPose_Orientation::clear_y() {
  y_ = 0;
}
inline double LoadPose_Orientation::_internal_y() const {
  return y_;
}
inline double LoadPose_Orientation::y() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.Orientation.y)
  return _internal_y();
}
inline void LoadPose_Orientation::_internal_set_y(double value) {
  
  y_ = value;
}
inline void LoadPose_Orientation::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadPose.Orientation.y)
}

// double z = 4;
inline void LoadPose_Orientation::clear_z() {
  z_ = 0;
}
inline double LoadPose_Orientation::_internal_z() const {
  return z_;
}
inline double LoadPose_Orientation::z() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.Orientation.z)
  return _internal_z();
}
inline void LoadPose_Orientation::_internal_set_z(double value) {
  
  z_ = value;
}
inline void LoadPose_Orientation::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:gz_pose_plugin.LoadPose.Orientation.z)
}

// -------------------------------------------------------------------

// LoadPose

// .gz_pose_plugin.LoadPose.Position position = 1;
inline bool LoadPose::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool LoadPose::has_position() const {
  return _internal_has_position();
}
inline void LoadPose::clear_position() {
  if (GetArena() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::gz_pose_plugin::LoadPose_Position& LoadPose::_internal_position() const {
  const ::gz_pose_plugin::LoadPose_Position* p = position_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gz_pose_plugin::LoadPose_Position*>(
      &::gz_pose_plugin::_LoadPose_Position_default_instance_);
}
inline const ::gz_pose_plugin::LoadPose_Position& LoadPose::position() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.position)
  return _internal_position();
}
inline void LoadPose::unsafe_arena_set_allocated_position(
    ::gz_pose_plugin::LoadPose_Position* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gz_pose_plugin.LoadPose.position)
}
inline ::gz_pose_plugin::LoadPose_Position* LoadPose::release_position() {
  auto temp = unsafe_arena_release_position();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gz_pose_plugin::LoadPose_Position* LoadPose::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:gz_pose_plugin.LoadPose.position)
  
  ::gz_pose_plugin::LoadPose_Position* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::gz_pose_plugin::LoadPose_Position* LoadPose::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::gz_pose_plugin::LoadPose_Position>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::gz_pose_plugin::LoadPose_Position* LoadPose::mutable_position() {
  // @@protoc_insertion_point(field_mutable:gz_pose_plugin.LoadPose.position)
  return _internal_mutable_position();
}
inline void LoadPose::set_allocated_position(::gz_pose_plugin::LoadPose_Position* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:gz_pose_plugin.LoadPose.position)
}

// .gz_pose_plugin.LoadPose.Orientation orientation = 2;
inline bool LoadPose::_internal_has_orientation() const {
  return this != internal_default_instance() && orientation_ != nullptr;
}
inline bool LoadPose::has_orientation() const {
  return _internal_has_orientation();
}
inline void LoadPose::clear_orientation() {
  if (GetArena() == nullptr && orientation_ != nullptr) {
    delete orientation_;
  }
  orientation_ = nullptr;
}
inline const ::gz_pose_plugin::LoadPose_Orientation& LoadPose::_internal_orientation() const {
  const ::gz_pose_plugin::LoadPose_Orientation* p = orientation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gz_pose_plugin::LoadPose_Orientation*>(
      &::gz_pose_plugin::_LoadPose_Orientation_default_instance_);
}
inline const ::gz_pose_plugin::LoadPose_Orientation& LoadPose::orientation() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPose.orientation)
  return _internal_orientation();
}
inline void LoadPose::unsafe_arena_set_allocated_orientation(
    ::gz_pose_plugin::LoadPose_Orientation* orientation) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(orientation_);
  }
  orientation_ = orientation;
  if (orientation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gz_pose_plugin.LoadPose.orientation)
}
inline ::gz_pose_plugin::LoadPose_Orientation* LoadPose::release_orientation() {
  auto temp = unsafe_arena_release_orientation();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gz_pose_plugin::LoadPose_Orientation* LoadPose::unsafe_arena_release_orientation() {
  // @@protoc_insertion_point(field_release:gz_pose_plugin.LoadPose.orientation)
  
  ::gz_pose_plugin::LoadPose_Orientation* temp = orientation_;
  orientation_ = nullptr;
  return temp;
}
inline ::gz_pose_plugin::LoadPose_Orientation* LoadPose::_internal_mutable_orientation() {
  
  if (orientation_ == nullptr) {
    auto* p = CreateMaybeMessage<::gz_pose_plugin::LoadPose_Orientation>(GetArena());
    orientation_ = p;
  }
  return orientation_;
}
inline ::gz_pose_plugin::LoadPose_Orientation* LoadPose::mutable_orientation() {
  // @@protoc_insertion_point(field_mutable:gz_pose_plugin.LoadPose.orientation)
  return _internal_mutable_orientation();
}
inline void LoadPose::set_allocated_orientation(::gz_pose_plugin::LoadPose_Orientation* orientation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete orientation_;
  }
  if (orientation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(orientation);
    if (message_arena != submessage_arena) {
      orientation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, orientation, submessage_arena);
    }
    
  } else {
    
  }
  orientation_ = orientation;
  // @@protoc_insertion_point(field_set_allocated:gz_pose_plugin.LoadPose.orientation)
}

// -------------------------------------------------------------------

// LoadPoseStamped

// .gz_pose_plugin.LoadHeader header = 1;
inline bool LoadPoseStamped::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool LoadPoseStamped::has_header() const {
  return _internal_has_header();
}
inline void LoadPoseStamped::clear_header() {
  if (GetArena() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::gz_pose_plugin::LoadHeader& LoadPoseStamped::_internal_header() const {
  const ::gz_pose_plugin::LoadHeader* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gz_pose_plugin::LoadHeader*>(
      &::gz_pose_plugin::_LoadHeader_default_instance_);
}
inline const ::gz_pose_plugin::LoadHeader& LoadPoseStamped::header() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPoseStamped.header)
  return _internal_header();
}
inline void LoadPoseStamped::unsafe_arena_set_allocated_header(
    ::gz_pose_plugin::LoadHeader* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gz_pose_plugin.LoadPoseStamped.header)
}
inline ::gz_pose_plugin::LoadHeader* LoadPoseStamped::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gz_pose_plugin::LoadHeader* LoadPoseStamped::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:gz_pose_plugin.LoadPoseStamped.header)
  
  ::gz_pose_plugin::LoadHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::gz_pose_plugin::LoadHeader* LoadPoseStamped::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::gz_pose_plugin::LoadHeader>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::gz_pose_plugin::LoadHeader* LoadPoseStamped::mutable_header() {
  // @@protoc_insertion_point(field_mutable:gz_pose_plugin.LoadPoseStamped.header)
  return _internal_mutable_header();
}
inline void LoadPoseStamped::set_allocated_header(::gz_pose_plugin::LoadHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:gz_pose_plugin.LoadPoseStamped.header)
}

// .gz_pose_plugin.LoadPose pose = 2;
inline bool LoadPoseStamped::_internal_has_pose() const {
  return this != internal_default_instance() && pose_ != nullptr;
}
inline bool LoadPoseStamped::has_pose() const {
  return _internal_has_pose();
}
inline void LoadPoseStamped::clear_pose() {
  if (GetArena() == nullptr && pose_ != nullptr) {
    delete pose_;
  }
  pose_ = nullptr;
}
inline const ::gz_pose_plugin::LoadPose& LoadPoseStamped::_internal_pose() const {
  const ::gz_pose_plugin::LoadPose* p = pose_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gz_pose_plugin::LoadPose*>(
      &::gz_pose_plugin::_LoadPose_default_instance_);
}
inline const ::gz_pose_plugin::LoadPose& LoadPoseStamped::pose() const {
  // @@protoc_insertion_point(field_get:gz_pose_plugin.LoadPoseStamped.pose)
  return _internal_pose();
}
inline void LoadPoseStamped::unsafe_arena_set_allocated_pose(
    ::gz_pose_plugin::LoadPose* pose) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose_);
  }
  pose_ = pose;
  if (pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gz_pose_plugin.LoadPoseStamped.pose)
}
inline ::gz_pose_plugin::LoadPose* LoadPoseStamped::release_pose() {
  auto temp = unsafe_arena_release_pose();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gz_pose_plugin::LoadPose* LoadPoseStamped::unsafe_arena_release_pose() {
  // @@protoc_insertion_point(field_release:gz_pose_plugin.LoadPoseStamped.pose)
  
  ::gz_pose_plugin::LoadPose* temp = pose_;
  pose_ = nullptr;
  return temp;
}
inline ::gz_pose_plugin::LoadPose* LoadPoseStamped::_internal_mutable_pose() {
  
  if (pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::gz_pose_plugin::LoadPose>(GetArena());
    pose_ = p;
  }
  return pose_;
}
inline ::gz_pose_plugin::LoadPose* LoadPoseStamped::mutable_pose() {
  // @@protoc_insertion_point(field_mutable:gz_pose_plugin.LoadPoseStamped.pose)
  return _internal_mutable_pose();
}
inline void LoadPoseStamped::set_allocated_pose(::gz_pose_plugin::LoadPose* pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete pose_;
  }
  if (pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(pose);
    if (message_arena != submessage_arena) {
      pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:gz_pose_plugin.LoadPoseStamped.pose)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gz_pose_plugin

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_load_5fpose_5fstamped_2eproto
